// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Updater;
//
//    var updateData = UpdateData.FromJson(jsonString);

namespace TEVL.Updater
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UpdateData
    {
        [JsonProperty("CurrentVersion", NullValueHandling = NullValueHandling.Ignore)]
        public string CurrentVersion { get; set; }
    }

    public partial class UpdateData
    {
        public static UpdateData FromJson(string json) => JsonConvert.DeserializeObject<UpdateData>(json, Updater.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this UpdateData self) => JsonConvert.SerializeObject(self, Updater.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
